version: '3.8'
services:
  app:
    container_name: degen-park-api
    image: degen-park-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: PGUSER
      POSTGRES_PASSWORD: PGPASS
    ports:
      - 5432:5432
    volumes:
      - monorepodata:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - 6666:6379
    volumes:
      - redisdata:/data
    
volumes:
  monorepodata:
    driver: local
  redisdata:
    driver: local