version: '3.8'
services:
  postgres:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: PGUSER
      POSTGRES_PASSWORD: PGPASS
    ports:
      - 5555:5432
    volumes:
      - monorepodata:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - 6666:6379
    volumes:
      - redisdata:/data
    
volumes:
  monorepodata:
    driver: local
  redisdata:
    driver: local